# Generated by Django 2.1 on 2020-03-10 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20181112_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField()),
                ('ratingfield', models.IntegerField(default=1)),
                ('suggestions', models.CharField(max_length=500)),
                ('assocourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('From_date', models.DateField(default='2020-03-01')),
                ('To_date', models.DateField(default='2020-03-01')),
                ('Reason', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default='False')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='startfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default='False')),
            ],
        ),
    ]
